### ISSUE TITLE
Potentially serious ethical violation

### ISSUE THREAD

**Issue by PlagueWizard** [libretro/netplay-lobby-server#12]
https://github.com/libretro/netplay-lobby-server/blob/94b35d37956837945b457fe19486b172c51cd529/lobbyapp/views.py#L152

Listing static ip addresses on a publicly viewable github seems incredibly unwise to me, if not from a Github TOS (not sure if it even is) standpoint then from an ethical one, as this information could be used to or seen as inciting harassment, and very definitely can be used to begin the process of doxing someone.

**Comment by m4xw** [comment]
You call this a ethical violation?
If you would know what these IP's did you would know what a serious ethical violation looks like.
