### ISSUE TITLE
New notifications are not sent when switching game

### ISSUE THREAD

**Issue by yisraeldov** [libretro/netplay-lobby-server#3]
To replicate:
* Start a netplay lobby
* See that there is a message sent to irc and discord
* Switch to a different game and start a netplay lobby
* No message is sent.

This is caused because successive `entries` from the same ip and port are treated as an update and not as a new entry

https://github.com/libretro/netplay-lobby-server/blob/master/lobbyapp/views.py#L145
``` python
    if entry.username == username and \
      entry.ip == ip and \
      entry.port == port:
        update = entry.id
        break

``` 

I had this same issue in the [Ajax notifications](https://github.com/yisraeldov/netplay-lobby-server/blob/d1eb58b7a642b8158908f265e2ff46befb25dfde/lobbyapp/templates/index.html#L114)

You can see how I fixed it there.

Or alternately you can test on something other than `update` to see if you need to send the irc/discord notifications. IMO a different game/core is not the same `entry` and should be added as a new one, not updated.

**Comment by yisraeldov** [comment]
I would fix this with a pull request, but I haven't been able to get the django app to work.

**Comment by bparker06** [comment]
The `update` parameter is for handling recurring announcements that come from RetroArch while the game is running, it wasn't designed to be used for switching the game someone is playing within the same lobby, we don't technically support that as it breaks MITM in more ways than one.

**Comment by bparker06** [comment]
Perhaps if an announcement comes in for the same ip/port but a different game/core, then maybe we can treat that as a whole new entry and just let the old one time out... that might be a suitable workaround to get a new notification and still keep MITM happy.

**Comment by fr500** [comment]
if IP and port match just nuke the old one I guess since you can't have two going on in the same IP:port combination. 

Nuke the old one and publish the new one as ... new

**Comment by bparker06** [comment]
@fr500 You could if you were using MITM and hosted 2 sessions; they would appear as the same IP/port (port being the hoster's port that's never actually used for MITM).

**Comment by fr500** [comment]
Ah yeah didn't think of that.
Well then maybe we can have a session ID calculated on the system at first run (RA being the system)

Then we can post that session ID. If the session ID is the same trump the old one?

**Comment by yisraeldov** [comment]
That was my proposal. Only set update if the core and game are the same ,
as well as IP and port.

**Comment by bparker06** [comment]
@yisraeldov check out 786dac9 and see if that works for you

**Comment by bparker06** [comment]
closing due to no response
